hotbars/hotbars/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from hotbarslocal import views
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hotbarslocal/', include('hotbarslocal.urls', namespace="hotbarslocal")),

    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),

]

urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })
]

hotbars/hotbarslocal/urls.py
from django.conf.urls import url
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from models import Bar, Drink
from forms import BarForm, DrinkForm
from views import BarCreate, DrinkCreate, BarDetail, review, signup

urlpatterns = [

# List latest Bars/
    url(r'home',
        ListView.as_view(
        	queryset=Bar.objects.all(),
        	context_object_name='latest_bar_list',
        	template_name='hotbarslocal/bar_list.html'),
        name='bar_list'),

# Restaurant details, ex.: /myrestaurants/restaurants/1/
    url(r'^bar/(?P<pk>\d+)/$',
        BarDetail.as_view(),
        name='bar_detail'),

# Restaurant dish details, ex: /myrestaurants/restaurants/1/dishes/1/
    url(r'^bars/(?P<pkr>\d+)/drinks/(?P<pk>\d+)/$',
        DetailView.as_view(
        	model=Drink,
        	template_name='hotbarslocal/drink_detail.html'),
        name='drink_detail'),

# Create a restaurant, /myrestaurants/restaurants/create/
    url(r'^bars/create/$',
        BarCreate.as_view(),
        name='bar_create'),

# Edit restaurant details, ex.: /myrestaurants/restaurants/1/edit/
    url(r'^bars/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
        	model = Bar,
        	template_name = 'hotbarslocal/form.html',
        	form_class = BarForm),
        name='bar_edit'),

# Create a restaurant dish, ex.: /myrestaurants/restaurants/1/dishes/create/
    url(r'^bars/(?P<pk>\d+)/drinks/create/$',
    	DrinkCreate.as_view(),
        name='drink_create'),

# Edit restaurant dish details, ex.: /myrestaurants/restaurants/1/dishes/1/edit/
    url(r'^bars/(?P<pkr>\d+)/drinks/(?P<pk>\\d+)/edit/$',
    	UpdateView.as_view(
    		model = Drink,
    		template_name = 'hotelbarslocal/form.html',
    		form_class = DrinkForm),
    	name='drink_edit'),



    url(r'^restaurants/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),
#URL for Signup PAGE VIEW
    url(r'^signup/$', signup, name='signup'),
]

hotbars/hotbarslocal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.


class Bar(models.Model):
    name = models.CharField(max_length=100)
    street = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    city = models.CharField(blank=True, max_length=50)
    zipCode = models.IntegerField(blank=True, null=True)
    state = models.CharField(blank=True, null=True, max_length=10)
    country = models.CharField(blank=True, null=True, max_length=10)
    telephone = models.IntegerField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('hotbarslocal:bar_detail', kwargs={'pk': self.pk})


class Drink(models.Model):
    name = models.CharField(max_length=50, null=True)
    description = models.TextField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to="DrinkPictures", blank=True, null=True)

    price = models.DecimalField('Dollar amount', max_digits=8, decimal_places=2, blank=True)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    image = models.ImageField(upload_to='mybars', blank=True, null=True)
    bar = models.ForeignKey(Bar, null=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('hotbarslocal:drink_detail', kwargs={'pkr': self.bar.pk, 'pk': self.pk})

class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True, blank=True)

class BarReview(Review):
    bar = models.ForeignKey(Bar)

hotbars/hotbarslocal/forms.py
from django.forms import ModelForm
from models import Bar, Drink

class BarForm(ModelForm):
  class Meta:
    model = Bar
    exclude = ('user', 'url')

class DrinkForm(ModelForm):
  class Meta:
    model = Drink
    exclude = ('user', 'bar')

hotbars/hotbarslocal/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from models import BarReview, Bar, Drink
from forms import BarForm, DrinkForm
#Decorator for Login only only lets users that are logged in to see
from django.contrib.auth.decorators import login_required

class BarDetail(DetailView):
    model = Bar
    template_name = 'hotbarslocal/bar_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BarDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = BarReview.RATING_CHOICES
        return context


class BarCreate(CreateView):
    model = Bar
    template_name = 'hotbarslocal/form.html'
    form_class = BarForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BarCreate, self).form_valid(form)


class DrinkCreate(CreateView):
    model = Drink
    template_name = 'hotbarslocal/form.html'
    form_class = DrinkForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.bar = Bar.objects.get(id=self.kwargs['pk'])
        return super(DrinkCreate, self).form_valid(form)




@login_required
def review(request, pk):
    bar = get_object_or_404(Bar, pk=pk)
    if BarReview.objects.filter(bar=bar, user=request.user).exists():
        BarReview.objects.get(bar=bar, user=request.user).delete()
    new_review = BarReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        bar=bar)
    new_review.save()
    return HttpResponseRedirect(reverse('hotbarslocal:bar_detail', args=(bar.id,)))

#Signup VIEW for New USers
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username', False)
            raw_password = form.cleaned_data.get('password1', False)
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'hotbarslocal/signup.html', {'form': form})

hotbars/templates/hotbarslocal/bar_detail.html
{% extends "hotbarslocal/base.html" %}

{% block content %}
<h1>
  {{ bar.name }}
  {% if user == bar.user %}
    (<a href="{% url 'hotbarslocal:bar_edit' bar.id %}">edit</a>)
  {% endif %}
</h1>

<h2>Address:</h2>

<p>
  {{ bar.street }}, {{ bar.number }} <br/>
  {{ bar.zipcode }} {{ bar.city }} <br/>
  {{ bar.stateOrProvince }} ({{ bar.country }})
</p>

<h2>Drinks
  {% if user %}
    (<a href="{% url 'hotbarslocal:drink_create' bar.id %}">add</a>)
  {% endif %}
</h2>

<ul>
  {% for drink in bar.drinks.all %}
    <li><a href="{% url 'hotbarslocal:drink_detail' bar.id drink.id %}">
    {{ drink.name }}</a></li>
  {% empty %}<li>Sorry, no drinks for this bar yet.</li>
  {% endfor %}
</ul>









<h3>Add Review</h3>

<form action="{% url 'hotbarslocal:review_create' bar.id %}" method="post">
  {% csrf_token %}

  Message: <textarea name="comment" id="comment" rows="4"></textarea>
  <p>Rating:</p>
  <p>
    {% for rate in RATING_CHOICES %}
      <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" />
      <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{rate.0|pluralize }}</label>
      <br/>
    {% endfor %}
  </p>
  <input type="submit" value="Review" />
</form>



<h2>Reviews: </h2>


     <table style="width:100%">
          <tr>
      <th>Rating</th>

      <th>Comments</th>
      <th>Posted by: </th>
  </tr>
  {% for review in bar.barreview_set.all %}




        <tr>


        <td>{{ review.rating }} star{{ review.rating|pluralize }}</td>
            <td>{{ review.comment }}</td>
        <td>{{ review.user }}</td>

        </tr>
 {% endfor %}
</table>





{% endblock %}

{% block footer %}

Created by {{ bar.user }}

{% endblock %}

hotbars/templates/hotbarslocal/bar_list.html
{% extends "hotbarslocal/base.html" %}

{% block content %}
<h1>

  Popular Bars:
    {% if user %}<a href="{% url 'hotbarslocal:bar_create' %}" class="btn btn-primary" type="button">Add</a>{% endif %}


</h1>



<table>

  <tr>
    <th>Bar Name:</th>
    {% for bar in latest_bar_list %}
  </tr>
  <tr>
    <td><a href="{% url 'hotbarslocal:bar_detail' bar.id %}">
    {{ bar.name }}</a></td>
  {% empty %}<li>Sorry, no Bar registered yet.</li>
  </tr>

</table>
{% endfor %}


{% endblock %}

hotbars/templates/hotbarslocal/base.html

{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>HotBarsLocal</title>
<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<style>
body,h1,h2,h3,h4,h5 {
    color: black;

    }
a:hover {
    color: grey;
}

table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}



</style>
<nav><br>
  <div class="w3-container">

    <h3 class="w3-padding-64"><b>Bars<br>App</b></h3>
  </div><div class="w3-bar-block">
        <div id="sidebar">
  {% block sidebar %}<ul><li><a href="http://127.0.0.1:8000/hotbarslocal/home/">Home</a></li></ul>{% endblock %}
</div>


        <div id="header">
    {% block header %}
        {% if user.username %}
            <p>User <i class="glyphicon glyphicon-user"></i> User: {{ user.username }} | <a href="{% url 'logout' %}?next={{request.path}}">logout</a></p>
        {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">login</a></p>
        {% endif %}
    {% endblock %}
</div>



<div id="content">
  {% block content %}
  {% if error_message %}<p><strong>{{ error_message}}</strong></p>{% endif %}
  {% endblock %}
</div>

<div id="footer">
  {% block footer %}{% endblock %}
</div>
  </div>
</nav>
<body>

<!-- Sidebar/menu -->

</body>
</html>

hotbars/templates/hotbarslocal/drink_detail.html
{% extends "hotbarslocal/base.html" %}

{% block content %}

<h1>
  {{ drink.name }}
  {% if user == drink.user %}
    (<a href="{% url 'hotbarslocal:drink_edit' drink.bar.id drink.id %}">edit</a>)
  {% endif %}
</h1>

<p>{{ drink.description }}</p>

{% if drink.image %}
  <p><img src="{{ drink.image.url }}"/></p>
{% endif %}

<p>Served by:
  <a href="{% url 'hotbarslocal:bar_detail' drink.bar.id %}">
    {{ drink.bar.name}}
  </a>
</p>

{% endblock %}

{% block footer %}
  Created by {{ drink.user }} on {{ drink.date }}
{% endblock %}

hotbars/templates/hotbarslocal/edit_form.html
{% extends "hotbarslocal/base.html" %}

{% block content %}

<form method="post" enctype="multipart/form-data" action="">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit"/>
</form>

{% endblock %}

hotbars/templates/hotbarslocal/form.html
{% extends "hotbarslocal/base.html" %}

{% block content %}

<form method="post" enctype="multipart/form-data" action="">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" class="btn btn-primary" value="Submit"/>
</form>

{% endblock %}